variables:
  NGINX_VERSION: 1.23.2
stages:
  - build
  - init
  - deploy

image: node:16.5.0

pages:
  stage: deploy
  cache:
    key:
      files:
        - package-lock.json
      prefix: npm
    paths:
      - node_modules/
  tags:
    - docker-build
  script:
    - export CI_TEST_BRANCH=stage
    - echo "$CI_COMMIT_BRANCH"
    - echo "$CI_TEST_BRANCH"
    - npm install
    - npm run build-stage
  artifacts:
    paths:
      - public
  only:
    - stage
